version: '2.1'
services:
  spark-master:
    build: livy-server
    container_name: spark-master
    ports:
      - "8080:8080" # spark master
      - "7077:7077" #
      - "8998:8998" # livy server
      - "18080:18080" # spark history server
    tty: true
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - ${PWD}/data_path:/var/data_path
      - ${PWD}/../target/scala-2.11/spark-etl-assembly-0.1.0-SNAPSHOT.jar:/tmp/jars/spark-etl-assembly-0.1.0-SNAPSHOT.jar
      - ${PWD}/../target/scala-2.11/tw-pipeline_2.11-0.1.0-SNAPSHOT.jar:/tmp/jars/tw-pipeline_2.11-0.1.0-SNAPSHOT.jar
    env_file: config.env

  spark-worker-1:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ${PWD}/data_path:/var/data_path
    env_file: config.env

  spark-worker-2:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ${PWD}/data_path:/var/data_path
    env_file: config.env

  postgres:
    container_name: "postgres"
    image: postgres:9.6
    volumes:
      - ${PWD}/postgres_mount/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    env_file: config.env

  webserver:
    container_name: "webserver"
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
      - postgres
    environment:
      - EXECUTOR=Local
      - AIRFLOW__CORE__FERNET_KEY=1uU2E6EgdCmdHKebTZjQYvhCzqv8Q597vULxXJy-blE=
      - FERNET_KEY=1uU2E6EgdCmdHKebTZjQYvhCzqv8Q597vULxXJy-blE=
    command: "webserver"
    volumes:
      - ${PWD}/data_path:/var/data_path
      - ${PWD}/../airflow/dags:/usr/local/airflow/dags
      - ${PWD}/../airflow/plugins:/usr/local/airflow/plugins
      - ${PWD}/../airflow/logs:/usr/local/airflow/logs
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - config.env

  scheduler:
    container_name: "scheduler"
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
      - webserver
    environment:
      - EXECUTOR=Local
      - AIRFLOW__CORE__FERNET_KEY=1uU2E6EgdCmdHKebTZjQYvhCzqv8Q597vULxXJy-blE=
      - FERNET_KEY=1uU2E6EgdCmdHKebTZjQYvhCzqv8Q597vULxXJy-blE=
    volumes:
      - ${PWD}/data_path:/var/data_path
      - ${PWD}/../airflow/dags:/usr/local/airflow/dags
      - ${PWD}/../airflow/plugins:/usr/local/airflow/plugins
      - ${PWD}/../airflow/logs:/usr/local/airflow/logs
    env_file:
      - config.env
